config/routes.rb
Rails.application.routes.draw do
  resources :empleados
  resources :empresas do
    get 'getjson'
    resources :pacientes
  end
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empleado.rb
class Empleado < ApplicationRecord
end

app/models/empresa.rb
class Empresa < ApplicationRecord
  validates :nombre, presence: true
  validates :ruc, presence: true
  has_many :pacientes, dependent: :destroy
  accepts_nested_attributes_for :pacientes, allow_destroy: true
  validates :ruc, uniqueness: true
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  belongs_to :empresa
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: [:show, :edit, :update, :destroy]

  # GET /empleados
  # GET /empleados.json
  def index
    @empleados = Empleado.find_by_sql("select * from empleados")
  end

  # GET /empleados/1
  # GET /empleados/1.json
  def show
  end

  # GET /empleados/new
  def new
    @empleado = Empleado.new
  end

  # GET /empleados/1/edit
  def edit
  end

  # POST /empleados
  # POST /empleados.json
  def create
    @empleado = Empleado.new(empleado_params)

    respond_to do |format|
      if @empleado.save
        format.html { redirect_to @empleado, notice: 'Empleado was successfully created.' }
        format.json { render :show, status: :created, location: @empleado }
      else
        format.html { render :new }
        #render  :json => {errors:  @empleado.errors}, status: 422
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empleados/1
  # PATCH/PUT /empleados/1.json
  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to @empleado, notice: 'Empleado was successfully updated.' }
        format.json { render :show, status: :ok, location: @empleado }
      else
        format.html { render :edit }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empleados/1
  # DELETE /empleados/1.json
  def destroy
    @empleado.destroy
    respond_to do |format|
      format.html { redirect_to empleados_url, notice: 'Empleado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empleado
      @empleado = Empleado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empleado_params
      params.require(:empleado).permit(:nombre1, :nombre2, :apellido1, :apellido2, :tipo_identificacion, :numero_identificacion, :genero, :fecha_nacimiento, :lugar_nacimiento, :telefono, :email, :edo_civil)
    end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: %i[show edit update destroy]
  add_breadcrumb 'Home', :root_path
  add_breadcrumb 'Empresas', :empresas_path
  skip_before_action :verify_authenticity_token

  def getjson
    render = render json: Empresa.find_by_sql(['SELECT * FROM empresas WHERE nombre LIKE ? OR ruc LIKE ?', "%#{params[:nombre]}%", "%#{params[:ruc]}%"])
  end

  def index
    add_breadcrumb 'index'
    # @empresas = Empresa.paginate(:page => params[:page],per_page: 30)
  end

  def show
    add_breadcrumb 'Mostrar'
  end

  def new
    add_breadcrumb 'Nuevo', new_empresa_path

    @empresa = Empresa.new
  end

  def edit
    add_breadcrumb 'Nuevo', edit_empresa_path
  end

  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
         #format.json { render :show, status: :created, location: @empresa }
      else
        #format.html { render :new }
       # render json: {errors:  @empresa.errors}, status: :unprocessable_entity
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_empresa
    @empresa = Empresa.find(params[:id])
  end

  def empresa_params
    params.require(:empresa).permit(:nombre, :ruc, :ubicacion, :telefono, :email, pacientes_attributes:
     [:id, :primer_nombre, :segundo_nombre, :primer_apellido, :segundo_apellido, :tipo_identificacion,
      :numero_identificacion,:genero, :fecha_nac, :lugar_nacimiento, :telefono, :grupo_sangre, :edo_civil , :_destroy])
  end
end

app/controllers/helpers/application_helper.rb
module ApplicationHelper

  def cabezera_nombre
    case  params[:controller]
    when "empresas"
      if params[:action] == 'new'
        "Registrar "+params[:controller].capitalize
      elsif params[:action] == 'edit'
        "Editar "+params[:controller].capitalize
      elsif params[:action] == 'index'
        "Listado de "+params[:controller].capitalize
      else params[:action] == 'new'
        params[:controller].capitalize
      end
    end
  end



end

app/controllers/helpers/empresas_helper.rb
module EmpresasHelper
end

app/controllers/helpers/home_helper.rb
module HomeHelper
end

app/controllers/helpers/pacientes_helper.rb
module PacientesHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index
 end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]
  before_action :set_default_params, only: [:new, :create,:edit,:update,:delete,:destroy]
  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to empresa_paciente_path(params[:empresa_id],paciente), notice: 'Paciente was successfully created.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    byebug
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to empresa_paciente_path(params[:empresa_id],paciente), notice: 'Paciente was successfully updated.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_default_params
      @empresa = params[:empresa_id]
    end

    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:primer_nombre, :segundo_nombre, :primer_apellido, :segundo_apellido, :tipo_identificacion, :numero_identificacion, :genero, :fecha_nac, :lugar_nacimiento, :telefono, :grupo_sangre, :edo_civil, :empresa_id)
    end
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/views/empleados/_form.html.erb
<%= simple_form_for(@empleado) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre1 %>
    <%= f.input :nombre2 %>
    <%= f.input :apellido1 %>
    <%= f.input :apellido2 %>
    <%= f.input :tipo_identificacion %>
    <%= f.input :numero_identificacion %>
    <%= f.input :genero %>
    <%= f.input :fecha_nacimiento %>
    <%= f.input :lugar_nacimiento %>
    <%= f.input :telefono %>
    <%= f.input :email %>
    <%= f.input :edo_civil %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/empleados/edit.html.erb
<h1>Editing Empleado</h1>

<%= render 'form', empleado: @empleado %>

<%= link_to 'Show', @empleado %> |
<%= link_to 'Back', empleados_path %>

app/views/empleados/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Empleados</h1>

<table>
  <thead>
    <tr>
      <th>Nombre1</th>
      <th>Nombre2</th>
      <th>Apellido1</th>
      <th>Apellido2</th>
      <th>Tipo identificacion</th>
      <th>Numero identificacion</th>
      <th>Genero</th>
      <th>Fecha nacimiento</th>
      <th>Lugar nacimiento</th>
      <th>Telefono</th>
      <th>Email</th>
      <th>Edo civil</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empleados.each do |empleado| %>
      <tr>
        <td><%= empleado.nombre1 %></td>
        <td><%= empleado.nombre2 %></td>
        <td><%= empleado.apellido1 %></td>
        <td><%= empleado.apellido2 %></td>
        <td><%= empleado.tipo_identificacion %></td>
        <td><%= empleado.numero_identificacion %></td>
        <td><%= empleado.genero %></td>
        <td><%= empleado.fecha_nacimiento %></td>
        <td><%= empleado.lugar_nacimiento %></td>
        <td><%= empleado.telefono %></td>
        <td><%= empleado.email %></td>
        <td><%= empleado.edo_civil %></td>
        <td><%= link_to 'Show', empleado %></td>
        <td><%= link_to 'Edit', edit_empleado_path(empleado) %></td>
        <td><%= link_to 'Destroy', empleado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empleado', new_empleado_path %>

app/views/empleados/new.html.erb
<h1>New Empleado</h1>

<%= render 'form', empleado: @empleado %>

<%= link_to 'Back', empleados_path %>

app/views/empleados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre1:</strong>
  <%= @empleado.nombre1 %>
</p>

<p>
  <strong>Nombre2:</strong>
  <%= @empleado.nombre2 %>
</p>

<p>
  <strong>Apellido1:</strong>
  <%= @empleado.apellido1 %>
</p>

<p>
  <strong>Apellido2:</strong>
  <%= @empleado.apellido2 %>
</p>

<p>
  <strong>Tipo identificacion:</strong>
  <%= @empleado.tipo_identificacion %>
</p>

<p>
  <strong>Numero identificacion:</strong>
  <%= @empleado.numero_identificacion %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @empleado.genero %>
</p>

<p>
  <strong>Fecha nacimiento:</strong>
  <%= @empleado.fecha_nacimiento %>
</p>

<p>
  <strong>Lugar nacimiento:</strong>
  <%= @empleado.lugar_nacimiento %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @empleado.telefono %>
</p>

<p>
  <strong>Email:</strong>
  <%= @empleado.email %>
</p>

<p>
  <strong>Edo civil:</strong>
  <%= @empleado.edo_civil %>
</p>

<%= link_to 'Edit', edit_empleado_path(@empleado) %> |
<%= link_to 'Back', empleados_path %>

app/views/empresas/_form.html.erb
<%= javascript_pack_tag "form_empresa" %>

<div id="form_empresa">
    <%= content_tag :div,
    id: 'empresa-form',
    data: {
        id: empresa.id,
        empresa: empresa.to_json(except: [:id, :created_at, :updated_at]),
        pacientes_attributes: empresa.pacientes.to_json(except: [:empresa_id, :created_at, :updated_at]),
     } do %>

        <div v-if="!Object.keys(errores).length == 0">
            <em> Han ocurrido algunos errores que evitan el guardado:</em>
        </div>
        <div v-for="value, key in errores">
            <div id="card-alert" class="card red">
                <div class="card-content white-text">
                    <transition>
                        <p><i class="fa fa-ban"></i> <b>{{key.toUpperCase()}} {{ value[0].toUpperCase() }}</b></p>
                    </transition>
                </div>
                <button type="button" class="close white-text" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
        </div>
    <div class="row">
        <div class="col s6">
                <label> Nombre de la empresa</label>
                <b-field label=""  >
                    <b-input v-model="empresa.nombre" placeholder="Empresa la Ponderosa C.A.(ejemplo)" v-validate="{required:true, regex: /[a-zA-Z0-9 -,.()]$/}" name="empresa_nombre"  id="empresa_nombre"  data-vv-as="Nombre de la empresa"></b-input>
                </b-field>
                <span v-if="errors.has('empresa_nombre')"  class="red-text-error ">
                    {{ errors.first('empresa_nombre') }}
                </span>
        </div>
        <div class=" col s6">
            <label>Ruc de la empresa</label>
            <b-field>
                <b-input placeholder="1760001550001 (ejemplo)"  v-model="empresa.ruc" data-vv-as="RUC de la empresa" name="empresa_ruc"  v-validate="'required|numeric'"></b-input>
            </b-field>
            <span v-if="errors.has('empresa_ruc')"  class="red-text-error ">
                    {{ errors.first('empresa_ruc') }}
            </span>
        </div>
    </div>
<br>    <div class="row">
        <div class="col s6">
            <label>Numero Telefonico</label>
            <b-field >
                <b-input placeholder="0056113368551 (ejemplo)" v-model="empresa.telefono" data-vv-as="Telefono de la empresa" name="empresa_telefono" v-validate="'required|numeric'"/>
            </b-field>
            <span v-if="errors.has('empresa_telefono')"  class="red-text-error ">
                    {{ errors.first('empresa_telefono') }}
            </span>
        </div>
        <div class=" col s6">
            <label>Email</label>
            <b-field>
            <b-input placeholder="correo@empresa.com (ejemplo)" v-model="empresa.email" v-validate="'required|email'" name="empresa_email" data-vv-as="Email de la empresa" name="empresa_email">
            </b-field>
            <span v-if="errors.has('empresa_email')"  class="red-text-error">
                {{ errors.first('empresa_email') }}
            </span>
        </div>
    </div>
    <br>

    <div class="row">
        <div class="col s12">
            <label for="direccion">Direccion</label>
            <b-field>
                <b-input  placeholder="Edificio Seven, Oficina 01 , Calle 1 , Capital (ejemplo)" v-model="empresa.ubicacion" v-validate="{required:true, regex: /[a-zA-Z0-9 -,.()]$/}" data-vv-as="Direccion de la empresa" name="empresa_direccion"   />
            </b-field>
            <span v-if="errors.has('empresa_direccion')"  class="red-text-error">
                    {{ errors.first('empresa_direccion') }}
                </span>
        </div>
    </div>
     <br>
        <b-tabs type="is-toggle" expanded>
            <b-tab-item label="Agregar Empleados">
                    <div v-for="(paciente, index) in empresa.pacientes_attributes">
                            <div v-if="paciente._destroy == '1'">
                                El paciente
                                <b>{{ paciente.primer_nombre }}</b> fue removido
                <button v-on:click="undoRemove(index)" class="waves-effect waves-light btn btn-sm ">
                                    Deshacer</button>
                            </div>
                            <div v-else>
                                <div class="row">
                                    <button v-on:click="removePaciente(index)" class="btn-floating btn-large waves-effect waves-light red">        <i class="fa fa-minus" aria-hidden="true"></i>
                                       borrar  </button>
                                </div>
                                <div class="row">
                                    <div class="input-field col s3">
                                        <label for="">Primer nombre </label>
                                        <input type="text" placeholder="Juan (ejemplo)" v-model= "paciente.primer_nombre" />
                                    </div>
                                    <div class="input-field col s3">
                                        <label for="">Segundo nombre </label>
                                        <input type="text" placeholder="Andres (ejemplo)"   v-model= "paciente.segundo_nombre" />
                                    </div>
                                    <div class="input-field col s3">
                                        <label for="">Primer apellido </label>
                                        <input type="text" placeholder="Gutierrez (ejemplo)" v-model= "paciente.primer_apellido" />
                                    </div>
                                    <div class="input-field col s3">
                                        <label for="">Segundo apellido </label>
                                        <input type="text"placeholder="Gonzalez(ejemplo)"  v-model= "paciente.segundo_apellido" />
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="input-field col s3">
                                        <v-select :options="options"  v-model="paciente.tipo_identificacion" placeholder= "Tipo de documento">
                                        </v-select>
                                    </div>
                                    <div class="input-field col s3">
                                        <label for="">Numero de indentificacion </label>
                                        <input type="text" v-model= "paciente.numero_identificacion"  placeholder="Numero de identificacion"/>
                                    </div>
                                    <div class="input-field col s3">
                                        <v-select :options="['Femenino','Masculino','No especificado']"  v-model= "paciente.genero" placeholder="Genero">
                                        </v-select>
                                    </div>
                                    <div class="input-field col s3">

                                        <div id="calendario">
                                                <datepicker v-model="paciente.fecha_nac" language="es" >
                                                <label>Fecha de Nacimiento</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s3">
                                        <label for="">Lugar nacimiento </label>
                                        <input type="text" v-model= "paciente.lugar_nacimiento" placeholder="Lugar de nacimiento"/>
                                    </div>
                                    <div class="input-field col s3">
                                        <label for="">Telefono </label>
                                        <input type="text" v-model= "paciente.telefono" placeholder="Telefono"/>
                                    </div>
                                    <div class="input-field col s3">
                                        <label for="Grupo de sangre"></label>
                                        <input type="text" v-model= "paciente.grupo_sangre" placeholder="Grupo Sangre"/>

                                    </div>
                                    <div class="input-field col s3">
                                        <label for="">Edo. civil </label>
                                        <input type="text" v-model= "paciente.edo_civil" placeholder="Edo Civil"/>
                                    </div>
                                </div>


                            </div>
                            <hr>
                        </div>
                        <div class="row">
                                <button v-on:click="addPaciente" class="waves-effect waves-light btn btn-sm "> Agregar </button>
                        </div>


            </b-tab-item>
            <b-tab-item label="Subir lote de pacientes"></b-tab-item>

        </b-tabs>
         <!--EMPLEADOS -->
        <button v-on:click="saveEmpresa" :disabled="errors.any()" class="waves-effect waves-light btn btn-sm "> Guardar </button>

        <% end %>


            <br />

        </div>

app/views/empresas/edit.html.erb
<%= render 'form', empresa: @empresa %>
<div class="divider"></div>
<%= link_to 'Mostrar', @empresa , class:"btn waves-effect  waves-light"%>
      <%= link_to 'Volver', empresas_path , class: "btn waves-effect waves-light" %>

app/views/empresas/index.html.erb
<p id="notice"><%= notice %></p>


<div id="indexEmpresa">
    <empresas></empresas>
</div>

app/views/empresas/new.html.erb
<%= render 'form', empresa: @empresa %>
<%= link_to empresas_path , class: "waves-effect waves-light btn gradient-45deg-purple-deep-orange" do%>
<i class="fa fa-left"></i>Volver
<% end %>

app/views/empresas/show.html.erb
<%= javascript_pack_tag "notificacion" %>

<div id="notificacion">
    <notificacion></notificacion>
</div>


<p id="notice"><%= notice %></p>
<p>
  <strong>Nombre:</strong>
  <%= @empresa.nombre %>
</p>
<p>
  <strong>Ruc:</strong>
  <%= @empresa.ruc %>
</p>

<p>
  <strong>Ubicacion:</strong>
  <%= @empresa.ubicacion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @empresa.telefono %>
</p>

<p>
  <strong>Email:</strong>
  <%= @empresa.email %>
</p>
<br>
<div class="divider"></div>
<br>
<div class="row">
    <%= link_to edit_empresa_path(@empresa), class: "waves-effect waves-light btn gradient-45deg-indigo-light-blue" do %>
    <i class="fa fa-pencil"></i> Editar
    <% end %>
    <%= link_to empresas_path , class: "waves-effect waves-light btn gradient-45deg-purple-deep-orange" do%>
    <i class="fa fa-undo"></i> Volver
    <% end %>

</div>

app/views/layouts/_content.html.erb
      <!--breadcrumbs start-->

      <div id="breadcrumbs-wrapper">
          <!-- Search for small screen -->
          <div class="header-search-wrapper grey lighten-2 hide-on-large-only">
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize">
          </div>
          <div class="container">
            <div class="row">
              <div class="col s10 m6 l6">
                <h5 class="breadcrumbs-title"></h5>
                <ol class="breadcrumbs">
                    <%= render_breadcrumbs :separator => ' / ' %>
                </ol>
              </div>
              <div class="col s2 m6 l6">
                <h5 class="breadcrumbs-title"></h5>
                <div class="breadcrumbs">
                    <p align="right">
                      <% if params[:action] == 'index'  %>
                        <%= link_to  "/#{controller_name}/new" ,class: "waves-effect waves-light  btn gradient-45deg-light-blue-cyan" do %>
                        <i class="fa fa-plus " aria-hidden="true"></i> Agregar <%= "#{controller_name}" %>
                        <% end %>
                      <% end %>
                    </div>
              </div>
          </div>
          </div>
        </div>
        <!--breadcrumbs end-->
        <!--start container-->
        <div class="container">
          <div class="row">
            <div class="col s12 m12 l12">
              <div class="card-panel gradient-shadow":
                <div clss="row">
                    <%= yield %>
                </div>
              </div>
            </div>
        </div>
      </section>
      <!-- END CONTENT -->
      <!-- //////////////////////////////////////////////////////////////////////////// -->
      <!-- START RIGHT SIDEBAR NAV-->

      <!-- END RIGHT SIDEBAR NAV-->
    </div>
    <!-- END WRAPPER -->
  </div>
  <!-- END MAIN -->
  <!-- //////////////////////////////////////////////////////////////////////////// -->
  <!-- START FOOTER -->
  <!-- END FOOTER -->

app/views/layouts/_footer.html.erb
<footer class="page-footer gradient-45deg-light-blue-cyan">
    <div class="footer-copyright">
      <div class="container">
        <span>Copyright ©
        <a class="grey-text text-lighten-2" href="http://nipse.online" target="_blank">NIPSE</a> All rights reserved.</span>
        <span class="right hide-on-small-only"> Design and Developed by <a class="grey-text text-lighten-2" href="https://thecoderun.com.ve">thecoderun</a></span>
      </div>
    </div>
  </footer>

app/views/pacientes/edit.html.erb
<%= render 'form', paciente: @paciente , empresa: @empresa %>

<%= link_to 'Show', empresa_paciente_path(@paciente) %> |
<%= link_to 'Back', empresa_pacientes_path %>

app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Primer nombre</th>
      <th>Segundo nombre</th>
      <th>Primer apellido</th>
      <th>Segundo apellido</th>
      <th>Tipo identificacion</th>
      <th>Numero identificacion</th>
      <th>Genero</th>
      <th>Fecha nac</th>
      <th>Lugar nacimiento</th>
      <th>Telefono</th>
      <th>Grupo sangre</th>
      <th>Edo civil</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.primer_nombre %></td>
        <td><%= paciente.segundo_nombre %></td>
        <td><%= paciente.primer_apellido %></td>
        <td><%= paciente.segundo_apellido %></td>
        <td><%= paciente.tipo_identificacion %></td>
        <td><%= paciente.numero_identificacion %></td>
        <td><%= paciente.genero %></td>
        <td><%= paciente.fecha_nac %></td>
        <td><%= paciente.lugar_nacimiento %></td>
        <td><%= paciente.telefono %></td>
        <td><%= paciente.grupo_sangre %></td>
        <td><%= paciente.edo_civil %></td>
        <td><%= link_to 'Show', empresa_paciente_path(params[:empresa_id],paciente) %></td>
        <td><%= link_to 'Edit', edit_empresa_paciente_path(params[:empresa_id],paciente.id) %></td>
        <td><%#= link_to 'Destroy', empresa_paciente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paciente',new_empresa_paciente_path %>

app/views/pacientes/new.html.erb
<%= render 'form', paciente: @paciente, empresa: @empresa %>

<%= link_to 'Back', empresa_pacientes_path %>

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Primer nombre:</strong>
  <%= @paciente.primer_nombre %>
</p>

<p>
  <strong>Segundo nombre:</strong>
  <%= @paciente.segundo_nombre %>
</p>

<p>
  <strong>Primer apellido:</strong>
  <%= @paciente.primer_apellido %>
</p>

<p>
  <strong>Segundo apellido:</strong>
  <%= @paciente.segundo_apellido %>
</p>

<p>
  <strong>Tipo identificacion:</strong>
  <%= @paciente.tipo_identificacion %>
</p>

<p>
  <strong>Numero identificacion:</strong>
  <%= @paciente.numero_identificacion %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @paciente.genero %>
</p>

<p>
  <strong>Fecha nac:</strong>
  <%= @paciente.fecha_nac %>
</p>

<p>
  <strong>Lugar nacimiento:</strong>
  <%= @paciente.lugar_nacimiento %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @paciente.telefono %>
</p>

<p>
  <strong>Grupo sangre:</strong>
  <%= @paciente.grupo_sangre %>
</p>

<p>
  <strong>Edo civil:</strong>
  <%= @paciente.edo_civil %>
</p>

<%#= link_to 'Edit', edit_paciente_path(@paciente) %> |
<%= link_to 'Back', empresa_pacientes_path %>